// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.28.2

package org.example.protoFiles;

public interface BooksOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Books)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<org.example.protoFiles.Book> 
      getBooksList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  org.example.protoFiles.Book getBooks(int index);
  /**
   * <code>repeated .Book books = 1;</code>
   */
  int getBooksCount();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  java.util.List<? extends org.example.protoFiles.BookOrBuilder> 
      getBooksOrBuilderList();
  /**
   * <code>repeated .Book books = 1;</code>
   */
  org.example.protoFiles.BookOrBuilder getBooksOrBuilder(
      int index);
}
