// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.28.2

package org.example.protoFiles;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string author = 2;</code>
   * @return The author.
   */
  java.lang.String getAuthor();
  /**
   * <code>string author = 2;</code>
   * @return The bytes for author.
   */
  com.google.protobuf.ByteString
      getAuthorBytes();

  /**
   * <code>string isbn = 3;</code>
   * @return The isbn.
   */
  java.lang.String getIsbn();
  /**
   * <code>string isbn = 3;</code>
   * @return The bytes for isbn.
   */
  com.google.protobuf.ByteString
      getIsbnBytes();

  /**
   * <code>int32 publicationYear = 4;</code>
   * @return The publicationYear.
   */
  int getPublicationYear();

  /**
   * <pre>
   * Genre of the book
   * </pre>
   *
   * <code>.Book.Category category = 5;</code>
   * @return The enum numeric value on the wire for category.
   */
  int getCategoryValue();
  /**
   * <pre>
   * Genre of the book
   * </pre>
   *
   * <code>.Book.Category category = 5;</code>
   * @return The category.
   */
  org.example.protoFiles.Book.Category getCategory();

  /**
   * <code>.Book.Publisher publisher = 6;</code>
   * @return Whether the publisher field is set.
   */
  boolean hasPublisher();
  /**
   * <code>.Book.Publisher publisher = 6;</code>
   * @return The publisher.
   */
  org.example.protoFiles.Book.Publisher getPublisher();
  /**
   * <code>.Book.Publisher publisher = 6;</code>
   */
  org.example.protoFiles.Book.PublisherOrBuilder getPublisherOrBuilder();
}
