// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.28.2

package org.example.protoFiles;

public interface BookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:BookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status message like success or failure
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Status message like success or failure
   * </pre>
   *
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Book information
   * </pre>
   *
   * <code>.Book book = 2;</code>
   * @return Whether the book field is set.
   */
  boolean hasBook();
  /**
   * <pre>
   * Book information
   * </pre>
   *
   * <code>.Book book = 2;</code>
   * @return The book.
   */
  org.example.protoFiles.Book getBook();
  /**
   * <pre>
   * Book information
   * </pre>
   *
   * <code>.Book book = 2;</code>
   */
  org.example.protoFiles.BookOrBuilder getBookOrBuilder();
}
