// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.28.2

package org.example.protoFiles;

/**
 * Protobuf type {@code Book}
 */
public final class Book extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:Book)
    BookOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      Book.class.getName());
  }
  // Use Book.newBuilder() to construct.
  private Book(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Book() {
    title_ = "";
    author_ = "";
    isbn_ = "";
    category_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.example.protoFiles.BookOuterClass.internal_static_Book_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.example.protoFiles.BookOuterClass.internal_static_Book_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.example.protoFiles.Book.class, org.example.protoFiles.Book.Builder.class);
  }

  /**
   * <pre>
   * Enum for book category
   * </pre>
   *
   * Protobuf enum {@code Book.Category}
   */
  public enum Category
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Default value
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * Fiction category
     * </pre>
     *
     * <code>FICTION = 1;</code>
     */
    FICTION(1),
    /**
     * <pre>
     * Non-fiction category
     * </pre>
     *
     * <code>NON_FICTION = 2;</code>
     */
    NON_FICTION(2),
    /**
     * <pre>
     * Science category
     * </pre>
     *
     * <code>SCIENCE = 3;</code>
     */
    SCIENCE(3),
    /**
     * <pre>
     * History category
     * </pre>
     *
     * <code>HISTORY = 4;</code>
     */
    HISTORY(4),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Category.class.getName());
    }
    /**
     * <pre>
     * Default value
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * Fiction category
     * </pre>
     *
     * <code>FICTION = 1;</code>
     */
    public static final int FICTION_VALUE = 1;
    /**
     * <pre>
     * Non-fiction category
     * </pre>
     *
     * <code>NON_FICTION = 2;</code>
     */
    public static final int NON_FICTION_VALUE = 2;
    /**
     * <pre>
     * Science category
     * </pre>
     *
     * <code>SCIENCE = 3;</code>
     */
    public static final int SCIENCE_VALUE = 3;
    /**
     * <pre>
     * History category
     * </pre>
     *
     * <code>HISTORY = 4;</code>
     */
    public static final int HISTORY_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Category valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Category forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return FICTION;
        case 2: return NON_FICTION;
        case 3: return SCIENCE;
        case 4: return HISTORY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Category>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Category> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Category>() {
            public Category findValueByNumber(int number) {
              return Category.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.example.protoFiles.Book.getDescriptor().getEnumTypes().get(0);
    }

    private static final Category[] VALUES = values();

    public static Category valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Category(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Book.Category)
  }

  public interface PublisherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Book.Publisher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string location = 2;</code>
     * @return The location.
     */
    java.lang.String getLocation();
    /**
     * <code>string location = 2;</code>
     * @return The bytes for location.
     */
    com.google.protobuf.ByteString
        getLocationBytes();
  }
  /**
   * <pre>
   * Nested message for Publisher information
   * </pre>
   *
   * Protobuf type {@code Book.Publisher}
   */
  public static final class Publisher extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Book.Publisher)
      PublisherOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        Publisher.class.getName());
    }
    // Use Publisher.newBuilder() to construct.
    private Publisher(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Publisher() {
      name_ = "";
      location_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protoFiles.BookOuterClass.internal_static_Book_Publisher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protoFiles.BookOuterClass.internal_static_Book_Publisher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protoFiles.Book.Publisher.class, org.example.protoFiles.Book.Publisher.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCATION_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object location_ = "";
    /**
     * <code>string location = 2;</code>
     * @return The location.
     */
    @java.lang.Override
    public java.lang.String getLocation() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        location_ = s;
        return s;
      }
    }
    /**
     * <code>string location = 2;</code>
     * @return The bytes for location.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLocationBytes() {
      java.lang.Object ref = location_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        location_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, location_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(location_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, location_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.protoFiles.Book.Publisher)) {
        return super.equals(obj);
      }
      org.example.protoFiles.Book.Publisher other = (org.example.protoFiles.Book.Publisher) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getLocation()
          .equals(other.getLocation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.protoFiles.Book.Publisher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.example.protoFiles.Book.Publisher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.example.protoFiles.Book.Publisher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.example.protoFiles.Book.Publisher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.protoFiles.Book.Publisher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Nested message for Publisher information
     * </pre>
     *
     * Protobuf type {@code Book.Publisher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Book.Publisher)
        org.example.protoFiles.Book.PublisherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.protoFiles.BookOuterClass.internal_static_Book_Publisher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.protoFiles.BookOuterClass.internal_static_Book_Publisher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.protoFiles.Book.Publisher.class, org.example.protoFiles.Book.Publisher.Builder.class);
      }

      // Construct using org.example.protoFiles.Book.Publisher.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        location_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.protoFiles.BookOuterClass.internal_static_Book_Publisher_descriptor;
      }

      @java.lang.Override
      public org.example.protoFiles.Book.Publisher getDefaultInstanceForType() {
        return org.example.protoFiles.Book.Publisher.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.protoFiles.Book.Publisher build() {
        org.example.protoFiles.Book.Publisher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.protoFiles.Book.Publisher buildPartial() {
        org.example.protoFiles.Book.Publisher result = new org.example.protoFiles.Book.Publisher(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.example.protoFiles.Book.Publisher result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.location_ = location_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.protoFiles.Book.Publisher) {
          return mergeFrom((org.example.protoFiles.Book.Publisher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.protoFiles.Book.Publisher other) {
        if (other == org.example.protoFiles.Book.Publisher.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLocation().isEmpty()) {
          location_ = other.location_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                location_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object location_ = "";
      /**
       * <code>string location = 2;</code>
       * @return The location.
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          location_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string location = 2;</code>
       * @return The bytes for location.
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string location = 2;</code>
       * @param value The location to set.
       * @return This builder for chaining.
       */
      public Builder setLocation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        location_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string location = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocation() {
        location_ = getDefaultInstance().getLocation();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string location = 2;</code>
       * @param value The bytes for location to set.
       * @return This builder for chaining.
       */
      public Builder setLocationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        location_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Book.Publisher)
    }

    // @@protoc_insertion_point(class_scope:Book.Publisher)
    private static final org.example.protoFiles.Book.Publisher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.protoFiles.Book.Publisher();
    }

    public static org.example.protoFiles.Book.Publisher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Publisher>
        PARSER = new com.google.protobuf.AbstractParser<Publisher>() {
      @java.lang.Override
      public Publisher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Publisher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Publisher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.protoFiles.Book.Publisher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int TITLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AUTHOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object author_ = "";
  /**
   * <code>string author = 2;</code>
   * @return The author.
   */
  @java.lang.Override
  public java.lang.String getAuthor() {
    java.lang.Object ref = author_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      author_ = s;
      return s;
    }
  }
  /**
   * <code>string author = 2;</code>
   * @return The bytes for author.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorBytes() {
    java.lang.Object ref = author_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      author_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ISBN_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object isbn_ = "";
  /**
   * <code>string isbn = 3;</code>
   * @return The isbn.
   */
  @java.lang.Override
  public java.lang.String getIsbn() {
    java.lang.Object ref = isbn_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      isbn_ = s;
      return s;
    }
  }
  /**
   * <code>string isbn = 3;</code>
   * @return The bytes for isbn.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIsbnBytes() {
    java.lang.Object ref = isbn_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      isbn_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PUBLICATIONYEAR_FIELD_NUMBER = 4;
  private int publicationYear_ = 0;
  /**
   * <code>int32 publicationYear = 4;</code>
   * @return The publicationYear.
   */
  @java.lang.Override
  public int getPublicationYear() {
    return publicationYear_;
  }

  public static final int CATEGORY_FIELD_NUMBER = 5;
  private int category_ = 0;
  /**
   * <pre>
   * Genre of the book
   * </pre>
   *
   * <code>.Book.Category category = 5;</code>
   * @return The enum numeric value on the wire for category.
   */
  @java.lang.Override public int getCategoryValue() {
    return category_;
  }
  /**
   * <pre>
   * Genre of the book
   * </pre>
   *
   * <code>.Book.Category category = 5;</code>
   * @return The category.
   */
  @java.lang.Override public org.example.protoFiles.Book.Category getCategory() {
    org.example.protoFiles.Book.Category result = org.example.protoFiles.Book.Category.forNumber(category_);
    return result == null ? org.example.protoFiles.Book.Category.UNRECOGNIZED : result;
  }

  public static final int PUBLISHER_FIELD_NUMBER = 6;
  private org.example.protoFiles.Book.Publisher publisher_;
  /**
   * <code>.Book.Publisher publisher = 6;</code>
   * @return Whether the publisher field is set.
   */
  @java.lang.Override
  public boolean hasPublisher() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.Book.Publisher publisher = 6;</code>
   * @return The publisher.
   */
  @java.lang.Override
  public org.example.protoFiles.Book.Publisher getPublisher() {
    return publisher_ == null ? org.example.protoFiles.Book.Publisher.getDefaultInstance() : publisher_;
  }
  /**
   * <code>.Book.Publisher publisher = 6;</code>
   */
  @java.lang.Override
  public org.example.protoFiles.Book.PublisherOrBuilder getPublisherOrBuilder() {
    return publisher_ == null ? org.example.protoFiles.Book.Publisher.getDefaultInstance() : publisher_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(author_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, author_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(isbn_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, isbn_);
    }
    if (publicationYear_ != 0) {
      output.writeInt32(4, publicationYear_);
    }
    if (category_ != org.example.protoFiles.Book.Category.UNKNOWN.getNumber()) {
      output.writeEnum(5, category_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getPublisher());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(author_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, author_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(isbn_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, isbn_);
    }
    if (publicationYear_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, publicationYear_);
    }
    if (category_ != org.example.protoFiles.Book.Category.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, category_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getPublisher());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.example.protoFiles.Book)) {
      return super.equals(obj);
    }
    org.example.protoFiles.Book other = (org.example.protoFiles.Book) obj;

    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getAuthor()
        .equals(other.getAuthor())) return false;
    if (!getIsbn()
        .equals(other.getIsbn())) return false;
    if (getPublicationYear()
        != other.getPublicationYear()) return false;
    if (category_ != other.category_) return false;
    if (hasPublisher() != other.hasPublisher()) return false;
    if (hasPublisher()) {
      if (!getPublisher()
          .equals(other.getPublisher())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
    hash = (53 * hash) + getAuthor().hashCode();
    hash = (37 * hash) + ISBN_FIELD_NUMBER;
    hash = (53 * hash) + getIsbn().hashCode();
    hash = (37 * hash) + PUBLICATIONYEAR_FIELD_NUMBER;
    hash = (53 * hash) + getPublicationYear();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + category_;
    if (hasPublisher()) {
      hash = (37 * hash) + PUBLISHER_FIELD_NUMBER;
      hash = (53 * hash) + getPublisher().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.example.protoFiles.Book parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protoFiles.Book parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protoFiles.Book parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protoFiles.Book parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protoFiles.Book parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.example.protoFiles.Book parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.example.protoFiles.Book parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protoFiles.Book parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.example.protoFiles.Book parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.example.protoFiles.Book parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.example.protoFiles.Book parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static org.example.protoFiles.Book parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.example.protoFiles.Book prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Book}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Book)
      org.example.protoFiles.BookOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.protoFiles.BookOuterClass.internal_static_Book_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.protoFiles.BookOuterClass.internal_static_Book_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.protoFiles.Book.class, org.example.protoFiles.Book.Builder.class);
    }

    // Construct using org.example.protoFiles.Book.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getPublisherFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      title_ = "";
      author_ = "";
      isbn_ = "";
      publicationYear_ = 0;
      category_ = 0;
      publisher_ = null;
      if (publisherBuilder_ != null) {
        publisherBuilder_.dispose();
        publisherBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.example.protoFiles.BookOuterClass.internal_static_Book_descriptor;
    }

    @java.lang.Override
    public org.example.protoFiles.Book getDefaultInstanceForType() {
      return org.example.protoFiles.Book.getDefaultInstance();
    }

    @java.lang.Override
    public org.example.protoFiles.Book build() {
      org.example.protoFiles.Book result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.example.protoFiles.Book buildPartial() {
      org.example.protoFiles.Book result = new org.example.protoFiles.Book(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.example.protoFiles.Book result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.author_ = author_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.isbn_ = isbn_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.publicationYear_ = publicationYear_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.category_ = category_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.publisher_ = publisherBuilder_ == null
            ? publisher_
            : publisherBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.example.protoFiles.Book) {
        return mergeFrom((org.example.protoFiles.Book)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.example.protoFiles.Book other) {
      if (other == org.example.protoFiles.Book.getDefaultInstance()) return this;
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getAuthor().isEmpty()) {
        author_ = other.author_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getIsbn().isEmpty()) {
        isbn_ = other.isbn_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getPublicationYear() != 0) {
        setPublicationYear(other.getPublicationYear());
      }
      if (other.category_ != 0) {
        setCategoryValue(other.getCategoryValue());
      }
      if (other.hasPublisher()) {
        mergePublisher(other.getPublisher());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              author_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              isbn_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              publicationYear_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              category_ = input.readEnum();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              input.readMessage(
                  getPublisherFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 1;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object author_ = "";
    /**
     * <code>string author = 2;</code>
     * @return The author.
     */
    public java.lang.String getAuthor() {
      java.lang.Object ref = author_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        author_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string author = 2;</code>
     * @return The bytes for author.
     */
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      java.lang.Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string author = 2;</code>
     * @param value The author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      author_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string author = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthor() {
      author_ = getDefaultInstance().getAuthor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string author = 2;</code>
     * @param value The bytes for author to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      author_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object isbn_ = "";
    /**
     * <code>string isbn = 3;</code>
     * @return The isbn.
     */
    public java.lang.String getIsbn() {
      java.lang.Object ref = isbn_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        isbn_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string isbn = 3;</code>
     * @return The bytes for isbn.
     */
    public com.google.protobuf.ByteString
        getIsbnBytes() {
      java.lang.Object ref = isbn_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        isbn_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string isbn = 3;</code>
     * @param value The isbn to set.
     * @return This builder for chaining.
     */
    public Builder setIsbn(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      isbn_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string isbn = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearIsbn() {
      isbn_ = getDefaultInstance().getIsbn();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string isbn = 3;</code>
     * @param value The bytes for isbn to set.
     * @return This builder for chaining.
     */
    public Builder setIsbnBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      isbn_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int publicationYear_ ;
    /**
     * <code>int32 publicationYear = 4;</code>
     * @return The publicationYear.
     */
    @java.lang.Override
    public int getPublicationYear() {
      return publicationYear_;
    }
    /**
     * <code>int32 publicationYear = 4;</code>
     * @param value The publicationYear to set.
     * @return This builder for chaining.
     */
    public Builder setPublicationYear(int value) {

      publicationYear_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 publicationYear = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPublicationYear() {
      bitField0_ = (bitField0_ & ~0x00000008);
      publicationYear_ = 0;
      onChanged();
      return this;
    }

    private int category_ = 0;
    /**
     * <pre>
     * Genre of the book
     * </pre>
     *
     * <code>.Book.Category category = 5;</code>
     * @return The enum numeric value on the wire for category.
     */
    @java.lang.Override public int getCategoryValue() {
      return category_;
    }
    /**
     * <pre>
     * Genre of the book
     * </pre>
     *
     * <code>.Book.Category category = 5;</code>
     * @param value The enum numeric value on the wire for category to set.
     * @return This builder for chaining.
     */
    public Builder setCategoryValue(int value) {
      category_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Genre of the book
     * </pre>
     *
     * <code>.Book.Category category = 5;</code>
     * @return The category.
     */
    @java.lang.Override
    public org.example.protoFiles.Book.Category getCategory() {
      org.example.protoFiles.Book.Category result = org.example.protoFiles.Book.Category.forNumber(category_);
      return result == null ? org.example.protoFiles.Book.Category.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * Genre of the book
     * </pre>
     *
     * <code>.Book.Category category = 5;</code>
     * @param value The category to set.
     * @return This builder for chaining.
     */
    public Builder setCategory(org.example.protoFiles.Book.Category value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000010;
      category_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Genre of the book
     * </pre>
     *
     * <code>.Book.Category category = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCategory() {
      bitField0_ = (bitField0_ & ~0x00000010);
      category_ = 0;
      onChanged();
      return this;
    }

    private org.example.protoFiles.Book.Publisher publisher_;
    private com.google.protobuf.SingleFieldBuilder<
        org.example.protoFiles.Book.Publisher, org.example.protoFiles.Book.Publisher.Builder, org.example.protoFiles.Book.PublisherOrBuilder> publisherBuilder_;
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     * @return Whether the publisher field is set.
     */
    public boolean hasPublisher() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     * @return The publisher.
     */
    public org.example.protoFiles.Book.Publisher getPublisher() {
      if (publisherBuilder_ == null) {
        return publisher_ == null ? org.example.protoFiles.Book.Publisher.getDefaultInstance() : publisher_;
      } else {
        return publisherBuilder_.getMessage();
      }
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    public Builder setPublisher(org.example.protoFiles.Book.Publisher value) {
      if (publisherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        publisher_ = value;
      } else {
        publisherBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    public Builder setPublisher(
        org.example.protoFiles.Book.Publisher.Builder builderForValue) {
      if (publisherBuilder_ == null) {
        publisher_ = builderForValue.build();
      } else {
        publisherBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    public Builder mergePublisher(org.example.protoFiles.Book.Publisher value) {
      if (publisherBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          publisher_ != null &&
          publisher_ != org.example.protoFiles.Book.Publisher.getDefaultInstance()) {
          getPublisherBuilder().mergeFrom(value);
        } else {
          publisher_ = value;
        }
      } else {
        publisherBuilder_.mergeFrom(value);
      }
      if (publisher_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    public Builder clearPublisher() {
      bitField0_ = (bitField0_ & ~0x00000020);
      publisher_ = null;
      if (publisherBuilder_ != null) {
        publisherBuilder_.dispose();
        publisherBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    public org.example.protoFiles.Book.Publisher.Builder getPublisherBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getPublisherFieldBuilder().getBuilder();
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    public org.example.protoFiles.Book.PublisherOrBuilder getPublisherOrBuilder() {
      if (publisherBuilder_ != null) {
        return publisherBuilder_.getMessageOrBuilder();
      } else {
        return publisher_ == null ?
            org.example.protoFiles.Book.Publisher.getDefaultInstance() : publisher_;
      }
    }
    /**
     * <code>.Book.Publisher publisher = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        org.example.protoFiles.Book.Publisher, org.example.protoFiles.Book.Publisher.Builder, org.example.protoFiles.Book.PublisherOrBuilder> 
        getPublisherFieldBuilder() {
      if (publisherBuilder_ == null) {
        publisherBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            org.example.protoFiles.Book.Publisher, org.example.protoFiles.Book.Publisher.Builder, org.example.protoFiles.Book.PublisherOrBuilder>(
                getPublisher(),
                getParentForChildren(),
                isClean());
        publisher_ = null;
      }
      return publisherBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:Book)
  }

  // @@protoc_insertion_point(class_scope:Book)
  private static final org.example.protoFiles.Book DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.example.protoFiles.Book();
  }

  public static org.example.protoFiles.Book getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Book>
      PARSER = new com.google.protobuf.AbstractParser<Book>() {
    @java.lang.Override
    public Book parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Book> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Book> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.example.protoFiles.Book getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

