// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: book.proto
// Protobuf Java Version: 4.28.2

package org.example.protoFiles;

public interface ISBNRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ISBNRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string isbn = 1;</code>
   * @return The isbn.
   */
  java.lang.String getIsbn();
  /**
   * <code>string isbn = 1;</code>
   * @return The bytes for isbn.
   */
  com.google.protobuf.ByteString
      getIsbnBytes();
}
